### ISSUE TITLE
Error running `google_stackdriver::default`

### ISSUE THREAD

**Issue by mistic** [tablexi/chef-google_stackdriver#28]
Hey guys,

I'm having a very strange error when I include the recipe `google_stackdriver::default` in a custom cookbook I have. I haven't configured any attribute for google_stackdriver cookbook because the stackdriver agent will run inside GCE machine.

```
    googlecompute:
    googlecompute: NameError
    googlecompute: ---------
    googlecompute: uninitialized constant #>::GoogleStackdriver
    googlecompute:
    googlecompute: Cookbook Trace:
    googlecompute: ---------------
    googlecompute: /var/chef/cache/cookbooks/google_stackdriver/recipes/default.rb:54:in `from_file'
    googlecompute:
    googlecompute: Relevant File Content:
    googlecompute: ----------------------
    googlecompute: /var/chef/cache/cookbooks/google_stackdriver/recipes/default.rb:
    googlecompute:
    googlecompute: 47:    package 'stackdriver-agent' do
    googlecompute: 48:      action node['google_stackdriver']['action']
    googlecompute: 49:      options '--force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"'
    googlecompute: 50:      only_if { node['google_stackdriver']['enable'] }
    googlecompute: 51:    end
    googlecompute: 52:  end
    googlecompute: 53:
    googlecompute: 54>> Chef::Resource::Template.send(:include, GoogleStackdriver::Helper)
    googlecompute: 55:
    googlecompute: 56:  template node['google_stackdriver']['config_path'] do
    googlecompute: 57:    source 'google_stackdriver_agent.erb'
    googlecompute: 58:    variables(
    googlecompute: 59:      :api_key => node['google_stackdriver']['api_key'],
    googlecompute: 60:      :collectd => node['google_stackdriver']['config_collectd'],
    googlecompute: 61:      :gcm => stackdriver_legacy? && google_stackdriver? ? false : google_stackdriver?
    googlecompute: 62:    )
    googlecompute: 63:    notifies :restart, 'service[stackdriver-agent]', :delayed
    googlecompute:
    googlecompute: System Info:
    googlecompute: ------------
    googlecompute: chef_version=13.3.42
    googlecompute: platform=debian
    googlecompute: platform_version=8.6
    googlecompute: ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
    googlecompute: program_name=chef-client worker: ppid=17430;start=20:37:29;
    googlecompute: executable=/opt/chef/bin/chef-client
    googlecompute:
    googlecompute:
    googlecompute: Running handlers:
    googlecompute: [2017-08-23T20:37:38+00:00] ERROR: Running exception handlers
    googlecompute: Running handlers complete
    googlecompute: [2017-08-23T20:37:38+00:00] ERROR: Exception handlers complete
    googlecompute: Chef Client failed. 0 resources updated in 08 seconds
    googlecompute: [2017-08-23T20:37:38+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
    googlecompute: [2017-08-23T20:37:38+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    googlecompute: [2017-08-23T20:37:38+00:00] ERROR: uninitialized constant #>::GoogleStackdriver
    googlecompute: [2017-08-23T20:37:38+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

@phoolish @estahn   Do u have any idea why I'm having this error?

**Comment by phoolish** [comment]
@mistic I haven't tested this cookbook with chef 13. Can you try running this cookbook against a v12 client install?

**Comment by kevinreedy** [comment]
I just confirmed that this is breaking in Chef 13 in test-kitchen. Chef 12 seems fine.

**Comment by phoolish** [comment]
@kevinreedy always open to a PR 😁

**Comment by kevinreedy** [comment]
@mistic I had no problem running this cookbook on Chef 13 with a run_list of either `recipe[google_stackdriver::default]` and `recipe[acme_stackdriver::default]`, which is a simple wrapper recipe that is just `include_recipe 'google_stackdriver'`.

What does your wrapper look like? Have you made any modifications to the `google_stackdriver` cookbook, like removing the libraries folder or similar?

**Comment by mistic** [comment]
Thanks for the answers @phoolish and @kevinreedy :)

At the moment the only thing I have inside my application wrapper cookbook is this line inside the `defaullt.rb` recipe:

```
# Install Stackdriver Agent
include_recipe 'google_stackdriver'
```

I don't use this cookbook in a runlist, I just use `include_recipe` to use it. Do u think that this could been causing the problem?

**Comment by mistic** [comment]
I found also an interesting thing, this is exactly my use case that is failing:

https://tickets.opscode.com/browse/COOK-3495

**Comment by mistic** [comment]
Hey guys problem solved and cookbook has run and installed. I don't know why but my `knife cookbook upload --include_dependencies` hasn't upload the libraries subfolders. After I have upload manually the cookbook to the chef server it worked. However now I have another problem

`Starting Stackdriver metrics collection agent: stackdriver-agentUnable to determine collectd endpoint!`

Are u using the new stackdriver install method of just passing `--write-gcm` ?

**Comment by phoolish** [comment]
@mistic can you create a separate ticket to address that problem?

I use berkshelf `berks upload` to upload to the chef server so I can't speak to the `knife cookbook upload issue`.

**Comment by kevinreedy** [comment]
@mistic echo @phoolish, you should definitely be using `berks upload` to upload your cookbooks rather than `knife cookbook upload`. In our training materials and on learn.chef.io, we only use Berkshelf to upload cookbooks (though we might have one slide that shows you the old terrible way).
